// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";
import "./globals.css";
import { WalletProvider } from "@/components/wallet-switcher";

// Initialize the Inter font
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <SessionWrapper>
          <WalletProvider>{children}</WalletProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
